Feature/update privacy page
nmshd/documentation pull request #154
Opened 2023-10-11 13:32 UTC by vinzlange

update privacy page

2023-11-13 07:17 UTC, jkoenig134 requested changes

2023-11-13 07:17 UTC, jkoenig134 commented on _docs_explore/23-privacy.md
> +1. Pseudonyms or technical identifiers like Enmeshed Addresses, Enmeshed Public Keys, Device Ids, etc. are personal data, if the system has the possibility of mapping these pseudonyms to real world p
```suggestion
## **What is Personal Data for enmeshed?**

The notion "Personal data that has been de-identified, encrypted or **pseudonymised** but can be used to re-identify a person remains personal data." does have many implications for enmeshed - as to any other solution.

We are no lawyers or respected data privacy experts within the community, thus our interpretation of the data privacy regulations is a very narrow one:

1. Pseudonyms or technical identifiers like enmeshed Addresses, enmeshed Public Keys, Device Ids, etc. are personal data, if the system has the possibility of mapping these pseudonyms to real world persons
```

2023-11-13 07:17 UTC, jkoenig134 commented on _docs_explore/23-privacy.md
Enmeshed -> enmeshed in this file, but not at the beginning of sentences

2023-12-05 21:52 UTC, stnmtz approved these changes

2023-12-06 07:52 UTC, stnmtz approved these changes

2023-12-06 07:53 UTC, jkoenig134 approved these changes

2023-12-06 07:53 UTC, merged