Chore/use dids
nmshd/documentation pull request #236
Opened 2024-07-04 06:54 UTC by Magnus-Kuhn

2024-07-04 06:56 UTC, Magnus-Kuhn commented
The address generation algorithm deviates in the hex strings case from Confluence - I checked it stepping through the runtime code

2024-08-06 12:27 UTC, jkoenig134 commented on _docs_explore/60-addresses.md
> +<!-- TODO: consider new enmeshed key types  -->
a TODO in an open PR, can you resolve this?

2024-08-06 13:42 UTC, jkoenig134 requested changes

2024-08-06 13:42 UTC, jkoenig134 commented on _docs_integrate/integration-example.md
> +        "peer": "did:e:prod.enmeshed.eu:dids:60326ff5075e0d7378990c",
```suggestion
        "peer": "did:e:_________________",
```

2024-08-06 13:42 UTC, jkoenig134 commented on _docs_integrate/integration-example.md
> +You can query the Connector's address via the route `/api/v2/Account/IdentityInfo`. If you are using the Demo Connector of this Tutorial, the address is `did:e:stage.enmeshed.eu:dids:54013af2a3bffe9d
you have referenced this address, but not updated the connectors baseurl

2024-08-13 07:26 UTC, jkoenig134 commented on _includes/rapidoc
please undo formatting here, your formatter destroyed that file :/

2024-08-13 07:26 UTC, jkoenig134 commented on _includes/rapidoc
`F1 -> save without formatting` is your friend for these include files.

2024-08-13 11:58 UTC, jkoenig134 approved these changes
LGTM. Make sure to use dids in all other PRs too.

2024-08-13 12:11 UTC, merged