Design Updates 2.0 (reviewed)
nmshd/documentation pull request #266
Opened 2024-09-24 12:03 UTC by 0LIW3R

I strictly reviewed our commit based on your feedback, thanks for that! The following mistakes should now be fixed: 

- We haven't touched content changes on pages, we haven't changed
- Removed all .DS_Store files
- Fixed errors on footer.html
- Removed changes in navigation links
- Fixed command line errors

Please feel free to check and comment

2024-09-24 12:32 UTC, jkoenig134 requested changes

2024-09-24 12:32 UTC, jkoenig134 commented on assets/fonts/work-sans/work-sans-v19-latin-500.woff2
can't we get these fonts from any CDN?

2024-09-24 12:32 UTC, jkoenig134 commented on assets/css/plstr.scss
I don't get this filename

2024-09-24 12:32 UTC, jkoenig134 commented on assets/fonts/work-sans/work-sans-v19-latin-500.woff2
same for other fonts.

2024-09-24 12:32 UTC, jkoenig134 commented on _includes/footer.html
> +<!-- FOOTER NEW -->
remove this comment please.

2024-09-24 12:32 UTC, jkoenig134 commented on _includes/footer.html
> +</div>
newline missing at the end of the file

2024-09-24 12:32 UTC, jkoenig134 commented on about.markdown
this file seems to be auto generated, why have you added this?

2024-09-24 12:32 UTC, jkoenig134 commented on assets/css/__overwrite.css
where is this file used?

2024-09-24 12:47 UTC, 0LIW3R commented on assets/fonts/work-sans/work-sans-v19-latin-500.woff2
No, that's not GDPR-conform.

2024-09-24 12:55 UTC, jkoenig134 commented on assets/fonts/work-sans/work-sans-v19-latin-500.woff2
ok.

2024-09-24 12:58 UTC, jkoenig134 commented
@0LIW3R please use the prettier cli to check formatting

2024-09-25 08:04 UTC, 0LIW3R commented on assets/css/__overwrite.css
To be honest, I don't know. This was in the template file. I think, it is for basic styling.

2024-09-25 08:16 UTC, 0LIW3R commented on assets/css/plstr.scss
Just changed to enmeshed

2024-09-25 08:16 UTC, 0LIW3R commented on _includes/footer.html
> +<!-- FOOTER NEW -->
Removed

2024-09-25 08:17 UTC, 0LIW3R commented on about.markdown
Removed

2024-09-25 08:24 UTC, jkoenig134 commented on _includes/head/custom.html
> +{% endif %}
please install the prettier extension in your vscode or run prettier, newline also missing here.

2024-09-25 08:24 UTC, jkoenig134 commented on _includes/head/custom.html
> +    what you are looking for?
why have you changed this?

2024-09-25 08:26 UTC, jkoenig134 commented on assets/css/__overwrite.css
If you look at your diff you see that this file WAS used before in `_includes/head/custom.html` and now it is unused. If you don't need it and have replaced it with your custom styling - why move it instead of remove it?

2024-09-25 08:32 UTC, jkoenig134 commented
> just checked it. It shouts an error on a duplicate closing p tag, but there isn't one.. I also checked the other tags but don't see any mistake.

There is a mistake, AFAIK <ul> may not be inside of a paragraph. that's why prettier is complaining.

2024-09-25 08:38 UTC, jkoenig134 commented
@vinzlange I updated to PR to match our codestyle, could you check if the design is ok?

2024-09-25 10:51 UTC, jkoenig134 commented
@0LIW3R your update broke our TOC

before:
![image](https://github.com/user-attachments/assets/a86379b2-d7e9-4552-a83a-79aba419d4ee)

after:
![image](https://github.com/user-attachments/assets/bb84970e-3807-4cfa-ab6f-506faf5ae77d)

TOC is not floating anymore.

2024-10-01 14:22 UTC, jkoenig134 commented
@0LIW3R your "FIX" destroyed the whole site.

![image](https://github.com/user-attachments/assets/afe670e9-5b75-4dfd-9eea-1663548554b3)

2024-10-01 14:56 UTC, 0LIW3R commented
> @0LIW3R your "FIX" destroyed the whole site.
> 
> ![image](https://private-user-images.githubusercontent.com/33655937/372505755-afe670e9-5b75-4dfd-9eea-1663548554b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTQ3MjMsIm5iZiI6MTcyNzc5NDQyMywicGF0aCI6Ii8zMzY1NTkzNy8zNzI1MDU3NTUtYWZlNjcwZTktNWI3NS00ZGZkLTllZWEtMTY2MzU0ODU1NGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0NTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTlmOGU3ZGZiZjc3NTEzNTc3NDA1M2FiNmZkYTFmN2UwYzQwNDEyYjhkNDljZTYyMmZiM2M2NmIwOWVhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kps-9QIUmvm4d_hXCYESe_fbEyc-utNpXkcS-OFlONQ)

Just checked again on my side, it's working fine locally.

2024-10-01 15:05 UTC, 0LIW3R commented
> @0LIW3R have you tried in dark mode?

Ah, thanks for clarification! I just removed the conflicting overwrites in the overwrite.css. Now TOC works and styles are correct both in light- and darkmode.

2024-10-01 15:05 UTC, jkoenig134 commented on assets/css/overwrite.css
> +}
newline.

2024-10-01 15:08 UTC, jkoenig134 reviewed
Looks okay to me. @vinzlange PTAL.

2024-10-01 15:08 UTC, jkoenig134 submitted a review, later dismissed

2024-10-02 10:00 UTC, jkoenig134 commented
@0LIW3R we found some issues with the dark mode:

The text in the blog pages does not have enough contrast
![image](https://github.com/user-attachments/assets/438af33f-2cf2-49f9-8315-2ce7a144d497)

The warning dialogs contrast is also not good (for example in http://localhost:4000/operate/configuration#debug)
![image](https://github.com/user-attachments/assets/8ffb14c7-2f31-4716-ab15-9b24427d797c)

2024-10-02 10:48 UTC, vinzlange commented on _layouts/use.html
that is no longer used and is just a remnant of the fingerprints?

2024-10-02 10:48 UTC, vinzlange commented on _config.yml
> +      icon: "fas fa-fw fa-user-shield"
the icons are no longer used in the current layout but why was this replaced?

2024-10-02 11:01 UTC, vinzlange reviewed
why is the footer displayed with an animation?

2024-10-15 19:03 UTC, 0LIW3R commented
@jkoenig134 @vinzlange Darkmode and footer config is updated now

2024-10-15 19:03 UTC, 0LIW3R commented on _layouts/use.html
I don't get the point. We mainly changed the layout of this page to add fingerprints as delivered in the figma design

2024-10-16 07:06 UTC, jkoenig134 commented
@0LIW3R please, PLEASE, run prettier before you commit and push...

Blog is better now, but dates have to little contrast:
![image](https://github.com/user-attachments/assets/47ae54d4-396f-4c67-80dc-e01e891813ec)

On hover the link color gets really bad:
![image](https://github.com/user-attachments/assets/a63357ad-0dac-4e26-b521-5756292acae6)

2024-10-16 13:54 UTC, 0LIW3R commented
Added the changes with included prettier check and updates

2024-10-16 13:56 UTC, jkoenig134 approved these changes
LGTM. @vinzlange please also leave a review.

2024-10-17 05:29 UTC, vinzlange approved these changes
I am fine with it

2024-10-17 05:53 UTC, merged