Personalization of Tokens and RelationshipTemplates
nmshd/documentation pull request #283
Opened 2024-11-14 16:34 UTC by Magnus-Kuhn

While the creators of the Tokens and Templates can also load the Token/Template, I didn't mention this to avoid bloat. I hope that owners won't know/ won't be scared by the fact that they will need to get them from the backbone if they onboard a new device

2024-11-14 16:50 UTC, jkoenig134 commented
> I hope that owners won't know/ won't be scared by the fact that they will need to get them from the backbone if they onboard a new device

yeah, this is no problem. App users don't care and Connectors doesn't sync.

2024-11-14 16:55 UTC, jkoenig134 requested changes
Only two small details. Additionally I have the feeling that there are some pages missing (createTokenQRcodeFor*)?

2024-11-14 17:05 UTC, britsta requested changes

2024-11-14 17:05 UTC, britsta commented on _docs_integrate/establish-relationships.md
> +### Personalize the RelationshipTemplate
Please put this section before the `### Successfully Created RelationshipTemplate` section and after the `### Input for Creating a RelationshipTemplate` section.

2024-11-15 09:16 UTC, Magnus-Kuhn commented on _docs_use-cases/use-case-transport-create-token-qr-code-for-own-relationshiptemplate.md
> +published: true
The excel has been updated o7

2024-11-15 09:43 UTC, Magnus-Kuhn commented
> Additionally I have the feeling that there are some pages missing (createTokenQRcodeFor*)?

There are only Template and File for * and both are here

2024-11-15 10:52 UTC, britsta approved these changes

2024-11-15 11:07 UTC, jkoenig134 approved these changes

2024-11-15 11:37 UTC, merged